name: 🌳 Extract branch name
description: Branch name extracted, sanitized and slugified from git reference

outputs:
  branch-name-extracted:
    description: Branch name extracted, sanitized and slugified
    value: ${{ steps.extract-branch-name.outputs.branch-name-extracted }}

runs:
  using: "composite"
  steps:
    - shell: bash
      id: extract-branch-name
      run: |
        echo "This action extracts branch name from git reference, sanitizes and slugifies it"
        echo "It also replaces the default branch name with 'latest' if the branch name is the default branch name"

        echo

        git_ref=$(echo ${{ github.ref }} | cut -d'/' -f 3)
        default_branch=${{ github.event.repository.default_branch }}
        head_ref=${{ github.head_ref }}

        echo "Git reference: '$git_ref'"
        echo "Default branch: '$default_branch'"
        if [ -z $head_ref ]; then
            echo "Head reference: No head reference"
        else
            echo "Head reference: '$head_ref'"
        fi

        echo

        if [ -z $head_ref ]; then
            echo "No head reference branch found, so using git reference as '$git_ref'"
            branch_name=$git_ref
        else
            echo "Head reference branch found, using it as '$head_ref'"
            branch_name=$head_ref
        fi

        echo

        echo "Sanitizing branch name by replacing all '/' with '-'"
        branch_name_sanitized=${branch_name//\//-}
        if [ "$branch_name_sanitized" = "$default_branch" ]; then
            echo "Branch name '$branch_name_sanitized' is the default repository branch name '$default_branch', so using 'latest' as branch name"
            branch_name_sanitized="latest"
        fi
        echo "Branch name sanitized and used as output: '$branch_name_sanitized'"
        echo branch-name-extracted=$branch_name_sanitized >> $GITHUB_OUTPUT
